name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CR_REGISTRY: crps36i3s1dfq9gn5nu5
  CR_REPO: catgpt
  IMAGE_TAG: ${{ github.sha }}
 
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v1.2.0
        with:
          yc-sa-json-credentials:  ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build and push image to Yandex Cloud CR
        run: |
          docker build --tag cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG
